namespace Whatsapp.web.net;

public enum DispatcherEventsType
{
    AUTHENTICATED,
    AUTHENTICATION_FAILURE,
    READY,
    CHAT_REMOVED,
    CHAT_ARCHIVED,
    MESSAGE_RECEIVED,
    MESSAGE_CIPHERTEXT, 
    MESSAGE_CREATE,
    MESSAGE_REVOKED_EVERYONE,
    MESSAGE_REVOKED_ME,
    MESSAGE_ACK,
    MESSAGE_EDIT,
    UNREAD_COUNT,
    MESSAGE_REACTION,
    MEDIA_UPLOADED,
    CONTACT_CHANGED,
    GROUP_JOIN,
    GROUP_LEAVE,
    GROUP_ADMIN_CHANGED,
    GROUP_MEMBERSHIP_REQUEST,
    GROUP_UPDATE,
    QR_RECEIVED,
    LOADING_SCREEN,
    DISCONNECTED,
    STATE_CHANGED,
    BATTERY_CHANGED,
    INCOMING_CALL,
    REMOTE_SESSION_SAVED
};